version: 2.1

# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist.);
orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
  aws-cli: circleci/aws-cli@1.4.0
  orb-tools: circleci/orb-tools@10.0.3

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-test-1:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Start Instance
          command: aws ec2 start-instances --instance-ids "$EC2_ID"
      - aws-code-deploy/push-bundle:
          application-name: "$APP_NAME"
          bundle-source: ./sample_app
          bundle-bucket: "$BUNDLE_BUCKET"
          bundle-key: "$BUNDLE_KEY"
      - aws-code-deploy/deploy-bundle:
          application-name: "$APP_NAME"
          deployment-group: "$DEPLOYMENT_GROUP_NAME"
          bundle-bucket: "$BUNDLE_BUCKET"
          bundle-key: "$BUNDLE_KEY"
      - run:
          name: Shutdown Instance
          command: aws ec2 stop-instances --instance-ids "$EC2_ID"

workflows:
  workflows:
    deploy_application:
      jobs:
        - aws-code-deploy/deploy:
            application-name: "$APP_NAME"
            bundle-bucket: "$BUNDLE_BUCKET"
            bundle-key: "$BUNDLE_KEY"
            deployment-group: "$DEPLOYMENT_GROUP_NAME"
            service-role-arn: "$SERVICE_ROLE_ARN"
